
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: knigboom-container
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    volumes:
      - .:/app
    restart: unless-stopped
